### ISSUE TITLE
Timed HeartBeat Messaging from WebClient to Devices

### ISSUE THREAD

**Issue by sjorsvanheuveln** [eclipse/paho.mqtt.javascript#109]
I would like to send timed messages on fixed intervals from the webclient to my devices in order to check whether my devices are still online. My devices have firmware that respond to some kind of heartbeat payload published to their topic. What's the best way to set up this in the web client in js. Is there already functionality in the client object or do I have to implement a new method?

**Comment by jpwsutton** [comment]
You would need to implement your own timer function, probably using something like this: https://stackoverflow.com/questions/3138756/calling-a-function-every-60-seconds

**Comment by sjorsvanheuveln** [comment]
I used the settimeout function in js to solve the issues. Thanks.
