### ISSUE TITLE
Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by StevenWash** [eclipse/paho.mqtt.javascript#112]
Hi @jpwsutton @knolleary ,
I have some problems when I use the client.subscribe,it will occur that 'Cannot read property 'subscribe' of undefined'.Then I find the client is undefined.But,I have use the client to connect,here are my code:
![image](https://user-images.githubusercontent.com/18731292/28863273-d708929c-779a-11e7-8390-1ddc154e62db.png)
When I click connect ,it will call the method 'connect()'.So,when I click connect in my web page,it will occur problems like that:
![image](https://user-images.githubusercontent.com/18731292/28863381-36eec848-779b-11e7-9fc1-d065da2ac1de.png)

And I guess that these method named 'onConnect,disconnect,onConnectionLost..' are belong to callback method,in these methods the client was undefine.But how can I deal these problems?

Any one can help me?Thank you very much!

**Comment by StevenWash** [comment]
Sorry,I have dealed these problems.
Thank you !

**Comment by jpwsutton** [comment]
@StevenWash Out of interest, what was your solution?

**Comment by StevenWash** [comment]
Because ,when callback to the onConnect method ,the scope is different from the scope before.So it need to bind the scope to the callback method.

**Comment by StevenWash** [comment]
@jpwsutton

**Comment by mer30boy** [comment]
I have same problem .what was your solution?
