### ISSUE TITLE
NPM Registry wrong version uploaded

### ISSUE THREAD

**Issue by kbariotis** [eclipse/paho.mqtt.javascript#137]
The version the NPM Registry is 1.0.4 but the latest version on this repository is 1.0.3. But the version that I have downloaded from the registry doesn't contain the latest version.

**Comment by pkuczynski** [comment]
@icraggs after #156 this one can be closed...

**Comment by icraggs** [comment]
Yay!  I can close it.  The NPM package has been updated at last.
