### ISSUE TITLE
How to get offline messages?

### ISSUE THREAD

**Issue by DayTimeDreamer** [eclipse/paho.mqtt.javascript#146]
Hello! How to get offline messages after reconnected? Thank you!

**Comment by jpwsutton** [comment]
Hi, If you are connecting with cleanSession=true then once you reconnect, the client will receive all messages that were published on it's subscriptions whilst it was offline.

**Comment by DayTimeDreamer** [comment]
@jpwsutton Hi! Thank you for your reply. I use paho.mqtt.javascript with mosca and set cleanSession=true, then it doesn't work.

**Comment by crmolinaz** [comment]
I think he means cleanSession=false

**Comment by icraggs** [comment]
So that could be a problem with Mosca?  You could try with another client library to verify.

**Comment by karlp** [comment]
you _also_ need to have a subscription from _before_ with a qos >= 1.  _and_ you need to reconnect using the _same_ client id.  It's not just "cleansession=false"
