### ISSUE TITLE
Npm version -> needs update

### ISSUE THREAD

**Issue by tmontanaro** [eclipse/paho.mqtt.javascript#156]
Hello, I'm trying to use paho mqtt in Vue loaded through Npm.
However, I saw that the latest version loaded on Npm is the 1.0.4 ([https://www.npmjs.com/package/paho-mqtt](https://www.npmjs.com/package/paho-mqtt) ), while here you are at the 1.2 version.

May I ask you why you did not update that version?

The reason behind this question:
I'm trying to use the library but, as soon as I connect to an MQTT broker through Websockects, the connection is immediately lost, as reported in this issue:

https://github.com/eclipse/paho.mqtt.java/issues/349

Could you please update the npm version?
Thank you in advance

**Comment by smellai** [comment]
Hi, we'd like to use npm with updated version too, thanks

**Comment by rogueturnip** [comment]
is anyone maintaining this to be able to do the npm update?

**Comment by pkuczynski** [comment]
Related also to #150

**Comment by icraggs** [comment]
Yes, it's down to me to look after this for the time being, but I'm spread over the Java, C, embedded C, V5 updates to Python.  Anyway, I'll get the NPM package updated.

**Comment by icraggs** [comment]
Are there two NPM packages?

@pkuczynski I would welcome some help!  Do you mean for the NPM package specifically or for this JavaScript library?  How would you like to help?  Thanks.

**Comment by pkuczynski** [comment]
Could help with both - with library and frequent releases of npm package :)

You would need to add me as a maintainer to this repo and to the npm.

**Comment by icraggs** [comment]
I can't just add someone to be a maintainer for this repo because becoming an Eclipse committer has a process: 

https://www.eclipse.org/projects/handbook/#elections-committer
https://www.eclipse.org/membership/become_a_member/committer.php

For the npm package I could add you, or will be able to once @jpwsutton has added me.  In that case you could help update the npm package, and make updates to this repo through PRs.  At some point you might like to become a committer too.  How does that sound?

**Comment by icraggs** [comment]
The NPM package has been updated to 1.1!  Sorry it took so long.

**Comment by pkuczynski** [comment]
Sure, we can start from npm :) Let me know when it's done...

**Comment by icraggs** [comment]
@jpwsutton updated the NPM package, after I asked him to add me as a maintainer :-)

What's your NPM id, the same as GitHub?

**Comment by pkuczynski** [comment]
Yup. `pkuczynski`
