### ISSUE TITLE
Multi-topic support for subscribe and unsubscribe

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.javascript#16]
migrated from Bugzilla [#473089](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473089)
status UNCONFIRMED severity *normal* in component *MQTT-JS* for *---*
Reported in version *1.0* on platform *All*
Assigned to: Ian Craggs

On 2015-07-20 11:10:56 -0400, James Sutton wrote:

> According to the API mqtt v3.1.1 spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718063), the client should be able to create one or more subscriptions. Currently the Javascript API only subscribes and unsubscribes to one topic at a time. This should be changed in order to match the specification.

**Comment by rokstefanic** [comment]
Hi. If you call subscribe multiple times, each time giving a different topic, the client will actually get subscribed to all those topics. At least this is how it seems to be working for me.

Any thoughts on this? (I have not checked the internals, just tried it out)

**Comment by jpwsutton** [comment]
Duplicate of #18
