### ISSUE TITLE
How can I know my message is sent successfully？

### ISSUE THREAD

**Issue by toBeGeekNo1** [eclipse/paho.mqtt.javascript#161]
hello, How can I know my message is successfully to sent the other? Is there have some info feedback? thanks

**Comment by PeterCAN** [comment]
Its not in the online documentation but have a look at the onMessageDelivered callback for the MQTTClient. In javascript at least it can be initialized like this...

```
myClient.onMessageDelivered = onMyMessageDelivered;

function onMyMessageDelivered()
{
    console.log("Your message was delivered");
}
```

If your send() is successful then the callback should be invoked.
