### ISSUE TITLE
Help ! how can I import this library in angular6.0

### ISSUE THREAD

**Issue by bestbelief** [eclipse/paho.mqtt.javascript#167]
i can not " npm install mqtt "for import this library in angular6.0, how i should do for import this library in angular6.0?? thank u very much!

**Comment by smellai** [comment]
why is not the last version on npm? 
https://www.npmjs.com/package/paho-mqtt

**Comment by bestbelief** [comment]
Maybe the Paha-mqtt library was not updated. Angular6 was released in May of this year.

**Comment by pkuczynski** [comment]
The latest version is on npm. @icraggs we can close this one I think...

**Comment by icraggs** [comment]
@pkuczynski I think 1.1.0 is on npm here: https://www.npmjs.com/package/paho-mqtt

Is that not correct?

**Comment by pkuczynski** [comment]
Ah! Indeed. I was blind. Should we then close this ticket?

**Comment by icraggs** [comment]
@pkuczynski Yes, we can close the ticket.  I've also added you as a maintainer for the NPM package now.  Thanks for following up here.
