### ISSUE TITLE
Uncaught ReferenceError: wireMessage is not defined

### ISSUE THREAD

**Issue by ctwj** [eclipse/paho.mqtt.javascript#168]
hello:
     i'm a newer, so i just use the example code in project. when connect everything is ok, but when i try to send something , i got the error `Uncaught ReferenceError: wireMessage is not defined`
Connect:
```
    this.client =new Paho.MQTT.Client('localhost', 8083, '')
   this.client.connect({
      onSuccess: this.onConnect,
      userName: 'test',
      password: 'test'
    });
```
Publish:
```
let message = new Paho.MQTT.Message('1');
    message.destinationName = "YZ_CONTROL";
    this.client.send(message);
```

ERROR:
>Uncaught ReferenceError: wireMessage is not defined
```
        # code where error happen
        wireMessage = new WireMessage(MESSAGE_TYPE.PUBLISH);
        wireMessage.payloadMessage = message;
```

**Comment by hgascoigne** [comment]
Hey there 👋 

I ran into the same issue and submitted a PR #170

**Comment by ctwj** [comment]
Ok , thankyou verymuch!
