### ISSUE TITLE
README.md points to invalid download page

### ISSUE THREAD

**Issue by Icidis** [eclipse/paho.mqtt.javascript#197]
Hi,

The README.md points to an invalid page on projects.eclipse.org. Where should it point to?

**Comment by Icidis** [comment]
After reading the mesage on the site it points out that you need t be logged into to access the project download area but with a really obscure message.

```
404 - Sorry! We couldn't find it.

Unfortunately, you don’t have permission to enter this area of the site.

If you are logged in and believe you should be able to access the page, please email us.
``` 

This shouldn't really be a 404 but rather a 403 and if the user is logged in then a 404.

I don't have a login to the site so i don't know if it actually is available.

**Comment by icraggs** [comment]
It should be: https://projects.eclipse.org/projects/iot.paho/downloads

I'll fix it.  Thanks for pointing it out.  The name changed quite a while back, but they both worked for a long while.

**Comment by icraggs** [comment]
Fixed.
