### ISSUE TITLE
Getting Error Code 8 - AMQJS0008I Socket closed

### ISSUE THREAD

**Issue by justinodle** [eclipse/paho.mqtt.javascript#198]
Using the default `keepAliveInterval` of 60 seconds I am consistently getting the error `AMQJS0008I Socket closed`. The error always occurs during the seccond ping request. I am using version 1.1.0 and connecting to a rabbitmq broker.

Here is the trace log from when `Client.connect` is called until the `onConnectionLost` callback is invoked:

```
Client.startTrace, "2019-05-21T18:39:42.892Z", "@VERSION@-@BUILDLEVEL@",Client.connect, {
  "keepAliveInterval":60,
  "reconnect":true,
  "mqttVersionExplicit":false,
  "mqttVersion":4,
  "cleanSession":true
}, 
null,
false,
Client._socket_send, {
  "type":1,
  "keepAliveInterval":60,
  "reconnect":true,
  "mqttVersionExplicit":false,
  "mqttVersion":4,
  "cleanSession":true,
  "clientId":"blossom"
},
Client._on_socket_message, 
{},
Client._handleMessage, 
{
  "type":2,
  "returnCode":0
},
Client.subscribe,
"#", 
{},
Client._socket_send, 
{
  "type":8,
  "topics":["#"],
  "requestedQos":[0],
  "messageIdentifier":1
},
Client._on_socket_message, 
{},
Client._handleMessage, 
{
  "type":9,
  "messageIdentifier":1,
  "returnCode":{"0":0}
},
Pinger.doPing, 
"send PINGREQ",
Client._on_socket_message, 
{},
Client._handleMessage, 
{"type":13},
Client._disconnected, 
8, 
"AMQJS0008I Socket closed.",
Client.getTraceLog, 
"2019-05-21T18:41:43.784Z",
Client.getTraceLog in flight messages,
```

**Comment by Zeleni9** [comment]
Hi I have the same issue but with Unity WebGL Mqqt Client. Did you maybe resolve the problem?

**Comment by break-paradigm** [comment]
Hello, I'm also experiencing the same problem. Did you resolve the problem?

**Comment by justinodle** [comment]
My issue was that I was trying to use the same client ID each time. The resolution was to use a randomly generated client ID. Hope it Helps!

**Comment by harshitaahuja** [comment]
I am generating random ids still facing this error. Anyone else facing similar issue?

**Comment by suwidadi** [comment]
> My issue was that I was trying to use the same client ID each time. The resolution was to use a randomly generated client ID. Hope it Helps!

I did this suggestion, and it worked...

**Comment by vmarques** [comment]
Same problem here, using paho js on web pages and mosquitto broker on a raspberry.
Error "AMQJS0008I Socket closed."
Trying to auto reconnect loops the problem.

Refreshing browser, recycles well, maybe due to bad declaration structure, my bad, 
but I had hope to get a clue on this discussion.

**Comment by sebastianha** [comment]
I do get this on test.mosquitto.org (wss), I get disconnected after 60s.
However, on my local installation (mosquitto 1.6.9, ws) it works without a problem.
Perhaps only a problem on test.mosquitto.org?

**Comment by suwidadi** [comment]
> I do get this on test.mosquitto.org (wss), I get disconnected after 60s.
> However, on my local installation (mosquitto 1.6.9, ws) it works without a problem.
> Perhaps only a problem on test.mosquitto.org?

Me too, disconnected but I put reconnecting when it does.

**Comment by sebastianha** [comment]
It's seems to be the case if you connect another client with the same client id. Just set it to something random:

```
var client = new Paho.Client(host, port, "client-" + Math.round(Math.random(100000000, 1000000000)*1000000000));
```

**Comment by hsddu** [comment]
how do you solove it?

> I am generating random ids still facing this error. Anyone else facing similar issue?

**Comment by vmarques** [comment]
> how do you solove it?
> 
> > I am generating random ids still facing this error. Anyone else facing similar issue?

Just redid the code flow, it minimized but not solved.

In fact, the socket closes while the declaration of "client" still valid, but w socket closed.
The socket seems to close by timeout.  A browser reload will get it working.
It's unclear what closes it, when and when to determine if it is closed or not.
