### ISSUE TITLE
How to publish a message using paho-mqtt?

### ISSUE THREAD

**Issue by vedant-dobby** [eclipse/paho.mqtt.javascript#202]
Is there some sort of documentation for this?

**Comment by vikahl** [comment]
It's in the readme (although not very clear).

Assuming that you have defined client as 
`var client = new Paho.MQTT.Client(location.hostname, Number(location.port), "clientId");` and _connected to the broker_, you can publish with:

```javascript
message = new Paho.MQTT.Message("Hello"); // message content as string
message.destinationName = "World"; // MQTT topic
client.send(message);
```

**Comment by vedant-dobby** [comment]
Thanks @vikahl .I solved it thanks
