### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by mafzal9** [eclipse/paho.mqtt.javascript#207]
Hi,

I made a web based MQTT Client using Paho JS Library at http://mqtt.run . when i use without ssl in my browser it works fine but if i use https version of client then its throwing the "SecurityError: The operation is insecure." error.

Need help on this so i make a proper working client for every one.

Best Regards,

**Comment by mafzal9** [comment]
@knolleary @jpwsutton

**Comment by knolleary** [comment]
Hi @mafzal9 

If you are serving the page over http then you will get that error if you try to create an HTTPS connection.

You'll need to serve the site over HTTPS.

**Comment by mafzal9** [comment]
@knolleary on http it's working fine. but if i move to https then it creates the problem.

**Comment by knolleary** [comment]
Are you accessing all resources using HTTPS as well?
You'll get that error if you try using the client from an HTTPS page with regular websockets rather than secure websockets.

**Comment by mafzal9** [comment]
yeah exactly so is it possible to access regular websocket using HTTPS instead of secure websockets?

**Comment by mafzal9** [comment]
actually i want to access localhost mqtt broker which i have setup without ssl and my website is using HTTPS. so i want to design a client which works for both websockets with ssl and without ssl.

**Comment by knolleary** [comment]
Most browser security configurations dont allow non-https connections from an HTTPS page as they are a security risk.

**Comment by mafzal9** [comment]
so what you suggest me that should i create an option on page for HTTPS and HTTP page for users ? or remove HTTPS from my website as it's just client for testing.

**Comment by knolleary** [comment]
I'm not suggesting anything - just explaining why you hit this error. How you choose to deal with it is up to you and your application.

**Comment by mafzal9** [comment]
Thanks @knolleary . i will spend some more time on this issue and find the outcome.

**Comment by vlw123** [comment]
@mafzal9, Any luck with running https version of client ? Actually I am also facing same issue ( "SecurityError: The operation is insecure." error )

**Comment by mafzal9** [comment]
@vlw123 still not.

**Comment by mafzal9** [comment]
@vlw123 it only works if you will connect with secure mqtt. for that reason you should configure SSL Certificates on MQTT Broker.

**Comment by vlw123** [comment]
@mafzal9 Thank you!

**Comment by vlw123** [comment]
@mafzal9 Try adding useSSL:true option while calling MQTT connect. It worked for me.

**Comment by mafzal9** [comment]
@vlw123 Thanks i will try it soon.
