### ISSUE TITLE
I'm having the error: WebSocket connection to 'wss://test.mosquitto.org:9001/mqtt' failed: WebSocket opening handshake timed out

### ISSUE THREAD

**Issue by lucaslgr** [eclipse/paho.mqtt.javascript#233]
I asked for help because I'm trying to connect on test.mosquitto.org with Paho Web Client JS but I have not been successful.

Here is my code:

```js
//MQTTT variable
var mqtt;
var reconnectTimeOut = 2000;
var host = "test.mosquitto.org";
//var host = "iot.eclipse.org";
//var port = 8080;
//var port = 8081;
//var port = 1883;
//var port = 1884;
//var port = 8883;
var port = 9001;

function onConnect() {
  console.log("Connected");
  mqtt.subscribe("controlproject/temperature");
}

function onMessageArrived(msg) {
  let temperature = parseInt(msg.payloadString);
  let today = new Date();
  let time =
    today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
  console.log(time, temperature);
}

function MQTTConnect() {
  console.log("Connecting to " + host + " in port " + port);
  mqtt = new Paho.MQTT.Client(host, Number(port), "webpage");
  mqtt.onMessageArrived = onMessageArrived;

  var options = {
	useSSL: true,
    timeout: 3,
    onSuccess: onConnect,
	onFailure: onFailure
  };

  mqtt.connect(options);
}

function onFailure(msg){
	console.log("Connection Attempt to Host " + host + " Failed");
	setTimeout(() => {MQTTConnect();}, reconnectTimeOut);
}
MQTTConnect();
```

Any one could help me ? I've tried many ports and in which one I got different errors, timeout, refused connection... This web page is running my code through a server with SSL. So, this is websocket over SSL.

Thanks guys!

**Comment by sectokia** [comment]
It seems to me the doc for the test page is wrong?
The test server accepts both WS and WSS on port 8081?

Using the following code:
`		<script src="mqttws31.js"></script>
		<SCRIPT>
		
function start()
{
	var clientId = "js12345678901234567890";
	var host = "test.mosquitto.org";
	//var port = 8080;
	//var port = 8081;
	//var port = 1883;
	//var port = 1884;
	//var port = 8883;
	var port = 8081;
	
	client = new Paho.MQTT.Client(host,port, clientId);
				
	client.connect({
		'timeout': 10,
		'keepAliveInterval': 20,
		'cleanSession': true,
		'useSSL': false,
		'invocationContext': {'clientId': clientId},
		'onSuccess': mqttConnectOK,
		'onFailure': mqttConnectFail
	});

}

function mqttConnectOK(obj)
{
	console.log('MQTT connected OK as clientId '+obj.invocationContext.clientId);
}

function mqttConnectFail(obj)
{
	console.log('MQTT Failed to Connect: '+obj.errorCode+' '+obj.errorMessage);
}`

For port 8081 I get "MQTT connected OK as clientId js12345678901234567890"
For port 8080 I get a websocket error ( WebSocket connection to 'ws://test.mosquitto.org:8080/mqtt' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR ) and the callback works ("MQTT Failed to Connect: 7 AMQJS0007E Socket error:undefined."

If I change useSSL to true the browser uses WSS, and the ports still do the same thing (ports on 8081, doesn't work on 8080).

**Comment by lucaslgr** [comment]
Hi @sectokia ! Thanks a lot for your explanation about the this problem. I just tried your example right now and it's working for me.
One more question please, where did you find about the parameters of JSON sent in method client.connect({}) ? Are there any documentation about them ?

**Comment by sectokia** [comment]
https://www.eclipse.org/paho/files/jsdoc/Paho.MQTT.Client.html

**Comment by lucaslgr** [comment]
@sectokia  Thanks very much again!
