### ISSUE TITLE
Unable to get connection status

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.javascript#34]
migrated from Bugzilla [#409773](https://bugs.eclipse.org/bugs/show_bug.cgi?id=409773)
status RESOLVED severity *minor* in component *MQTT-JS* for *---*
Reported in version *v0.5* on platform *PC*
Assigned to: Andrew Banks

On 2013-06-03 14:30:06 -0400, Alexander Rust wrote:

> Hi again, 
> 
> so far I've been unable to get the connection status of the Messaging.Client. 
> 
> If one disconnects when the client is not connected, it throws an INVALID_STATE that basically wrecks the client. Thus it would be good to have the possibility to check the connection state of the client to prevent such errors. 
> 
> Maybe I'm mistaken, but ClientImpl.prototype.connected is also listed below Messaging Client private instance members.
> 
> Is there really no method to check the connection status? 
> If so, is there any reason behind this?

On 2014-06-06 05:43:01 -0400, Al Stockdill-Mander wrote:

> The Client object now provides an isConnected() function

**Comment by michaeljota** [comment]
This is still valid? Because the method is no documented.
