### ISSUE TITLE
using phao library js

### ISSUE THREAD

**Issue by uxud** [eclipse/paho.mqtt.javascript#65]
Hi, i want to use this library i dont know how to include it in my html page. Do i need to download the file. <script src="mqttws31.js"></script>
im trying to follow this http://www.hivemq.com/blog/mqtt-client-library-encyclopedia-paho-js
to create a simple mqtt client to a page.
thank you in advance.

**Comment by jpwsutton** [comment]
Hi,

A good place to look at as an example is the included utility in this repository: https://github.com/eclipse/paho.mqtt.javascript/blob/master/utility/index.html

You just need to download this file: https://raw.githubusercontent.com/eclipse/paho.mqtt.javascript/master/src/mqttws31.js

Include it in your HTML like so:

```
<script src="mqttws31.js"></script>
```

And then write your javascript to work with it either inline in your html or in a separate javascript file.
