### ISSUE TITLE
Password is required

### ISSUE THREAD

**Issue by Klaster1** [eclipse/paho.mqtt.javascript#67]
The server I connect to uses username only for authentication, so I wan't to omit it from options passed to `connect`. But [this line of mqttws31.js](https://github.com/larrytin/paho.mqtt.javascript/blob/master/src/mqttws31.js#L1709) specifies that password option should be of "string" type.

Luckily, I can set `password: null` as a prototype property in order to bypass [type validation](https://github.com/larrytin/paho.mqtt.javascript/blob/master/src/mqttws31.js#L131-L132):

```
		client.connect(Object.assign(Object.create({
			password: null
		}), {
			userName,
                        // ...
		}))
```

Maybe something should be done about it?

**Comment by jpwsutton** [comment]
Hi, when you set your connect options do you set password? If you do not set any password property in the connectOptions, then it should be left null.

**Comment by Klaster1** [comment]
When I don't set password and set userName, the following error is thrown:

`mqttws31.js:1741 Uncaught Error: AMQJS0013E Invalid argument undefined for connectOptions.password.`

If I set password to null, then I get another error thrown by validate function:

`AMQJS0012E Invalid type object for password.validate @ mqttws31.js:138`

**Comment by jpwsutton** [comment]
Looks like the if statement responsible for checking if a password had been supplied without a username had been switched. I've resolved this and delivered the changes to the develop branch which should move to release at the beginning of June.
