### ISSUE TITLE
password protect problem

### ISSUE THREAD

**Issue by pokal4u** [eclipse/paho.mqtt.javascript#73]
HI,

I connected client with username and password successfully like:

var client = new Paho.MQTT.Client("domain.com", Number(port),  "myClientId" + new Date().getTime());
client.connect({userName : "username",password : "123456",onSuccess:onConnect,onFailure:doFail});

with above code all working fine, problem is how to protect my password because password is open for user when see in view page source, then user can  send messages directly to subscribers using below client

http://www.eclipse.org/paho/clients/js/utility/index.html

how can I prevent this?

Thanks

**Comment by miketran78727** [comment]
You don't want to have user id and password in your JavaScript source code.  You can dynmaically create input entries for user name and password from your html/JavaScript code.  Please check this out:  http://www.w3schools.com/jsref/dom_obj_password.asp

**Comment by TeddyBbear** [comment]
And to not have the userid/password flying across the net in plain text you want to use an SSL connection.
 

 

 

-----Original Message-----

**Comment by pokal4u** [comment]
If I set dynamic from javascript like

var x = document.createElement("INPUT");
x.setAttribute("type", "password"); 
x.setAttribute("value", "123456"); 

Then also user can see the password in above code using inspect element(F12)

**Comment by pokal4u** [comment]
any other ways to connect with password?

**Comment by miketran78727** [comment]
This is HTML and JavaScript Q&A, not an issue within the the scope of Paho JavaScript client.

Why do you set password in the code x.setAttribute("value", "123456") ?  You want the end user to manually enter the user id and password and your code just read the values.

**Comment by pokal4u** [comment]
Yes your correct, but problem is when user enter username and password we need to add username and password into pwfile, how? I mean how to create username and password programmatically?

if password is hiding I need to use single username and password.

**Comment by miketran78727** [comment]
By design, javascript does not have permission to read and write to local file. If you allow the end user to create username and password and then save them, you need to use Ajax and a server (e.g. MQTT broker) to read and write data (user name and password)  But again, you still want to protect the data read/wrote from/to the server by some form of security authentication.

**Comment by pokal4u** [comment]
how?

Please explain with any example.

**Comment by miketran78727** [comment]
Here is one way to write data to the HTTP server.  I will show how to do this with PHP.  To make it simple, I would use the same server for serving HTTP and MQTT (e.g. mosquitto).  So your html and java scripts will be served on that server.

Let's start with setup..  Below are specific to RHEL, check documentation for other linux distributions:
Install httpd, php
  yum install http
  yum install php

Post install setup

    Modify httpd.conf to point DocumentRoot  to "/" directory:
        In /etc/httpd/conf/httpd.conf, search for DocumentRoot, change the path to "/"
    Add apache user to root group, i.e:
        usermod -G root apache
    Change permission on the DocumentRoot directory, give root group owner full access:
        chmod -R g=rwx /sources
        (so if you put mqtttws31.js in /sources, then the html page will have this:
              <script type="text/javascript" charset="UTF-8" src="/sources/mqttws31.js"></script>
    Restart httpd server:
        /etc/init.d/httpd restart
    To have HTTP server starts automatically on reboots:
        chkconfig httpd on


Here is the PHP source code to write data to a file, writeData.php (must be put in /sources)
<?php
$filename = $_POST['FILENAME'];
$data = $_POST['DATA'];
if (($filename <> "") and ($data <> "")) {
	$fp = fopen($filename, 'a') or die ('Can not open $filename');
	flock($fp,LOCK_EX);
	fwrite($fp,$data);
	fclose($fp);
	echo "$data";
}
?>


Now the JavaScript source that will do Ajax call to invoke the writeData.php script:

// This function will obtain and return the HTTP request object
function getXMLHttp()
{
  var xmlHttp;

  try
  {
    //Firefox, Opera 8.0+, Safari
    xmlHttp = new XMLHttpRequest();
  }
  catch(e)
  {
    //Internet Explorer
    try
    {
      xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
    }
    catch(e)
    {
      try
      {
        xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
      }
      catch(e)
      {
        alert("Your browser does not support AJAX!")
        return false;
      }
    }
  }
  return xmlHttp;
}

/**
 * Write a message to the specified log file.
 */
function writeLog(filename, message){
	var url = "writeData.php";
	xmlhttp = getXMLHttp();
	
	xmlhttp.open("POST", url, true);
	var data = encodeURIComponent(message + "\n");
	params = "DATA=" + data + '&FILENAME=' + filename;
	xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	xmlhttp.setRequestHeader("Content-length", params.length);
	xmlhttp.setRequestHeader("Connection", "close");

	xmlhttp.onreadystatechange = function() {
		//Call a function when the state changes.	
		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
			//Do nothing!!!
		}
	}
	xmlhttp.send(params);
	//Echo the message back to the browser
	document.body.appendChild(document.createElement("br"));
	document.body.appendChild(document.createTextNode(message));
}
