### ISSUE TITLE
Getting NS_ERROR_NOT_CONNECTED on Firefox

### ISSUE THREAD

**Issue by azizhk** [eclipse/paho.mqtt.javascript#75]
I am getting it on this line of the library: https://github.com/eclipse/paho.mqtt.javascript/blob/65b0bf09f2323c6de1a26ce5c4ee79ccc31ba75e/src/mqttws31.js#L699

Can you let me know if and how I can add a check that `this._client.socket` is connected?

**Comment by jpwsutton** [comment]
Hi, what version of firefox are you using? Do you see the same behaviour if you use the online utility? https://www.eclipse.org/paho/clients/js/utility/

**Comment by azizhk** [comment]
We use this tool known as [Errorception](https://errorception.com/) to track Javascript Errors from our client's browser.
![screen shot 2016-07-25 at 2 32 26 pm](https://cloud.githubusercontent.com/assets/5094296/17096043/191cfa0c-5275-11e6-88db-beb02152895b.png)
I will check the online utility and let you know.

**Comment by azizhk** [comment]
I tried the utility. I could not reproduce the error though.
I suspect this might be related to some firefox plugin to optimize memory which would put tabs to sleep on inactivity. (Wild Guess, I have no idea about mqtt, I am just trying to debug some legacy code.)

**Comment by jpwsutton** [comment]
That would most likely explain it, the server will end the connection if the client has not sent a PING to it in the after the keepalive has expired.

**Comment by termvader** [comment]
Ok so the server has disconnected, do we get a callback or can we have a check so that we can stop Pinger from doing doPing?

**Comment by azizhk** [comment]
Ok so the server has disconnected, do we get a callback or can we have a check so that we can stop Pinger from doing doPing?

**Comment by miketran78727** [comment]
The callback is `onConnectionLost` 

Are you seeing the Pinger continues to do doPing after onConnectionLost ?

**Comment by jpwsutton** [comment]
Hi @azizhk, can I close this issue? Or are you still experiencing problems?

**Comment by termvader** [comment]
I've added an ignore flag in my error logger.
@miketran78727 I think so Pinger does do doPing but it does not come in onConnectionLost.

Some context: I use mqtt for an alternate tracking solution along with google analytics. I don't get any data loss so assuming that this error does not hinder me in any way.

Yes @jpwsutton you can close this issue.
