### ISSUE TITLE
Username creation

### ISSUE THREAD

**Issue by pokal4u** [eclipse/paho.mqtt.javascript#77]
Hi,
Creating username and password using below command in command line working fine.
"mosquitto_passwd /etc/mosquitto/passwd guest"
Same thing how to create in php or javascipt?
if possible we have lakhs of users, any perfomance issues with increased passwd file size?
Thanks

**Comment by jpwsutton** [comment]
This question is not related to the Paho MQTT javascript client, but actually Mosquitto. Please direct your question here: https://mosquitto.org/support/
