### ISSUE TITLE
Mosquitto keeps disconnecting. 

### ISSUE THREAD

**Issue by post2web** [eclipse/paho.mqtt.javascript#79]
I cannot connect to the mosquitto server. Here is the message I get when attempt to connect:
`1471693689: New connection from 127.0.0.1 on port 1883.`
`1471693689: Socket error on client <unknown>, disconnecting.`
Here is my javascript code:
```

	client = new Paho.MQTT.Client('127.0.0.1', 1883, 'clientId32');
	client.onConnectionLost = onConnectionLost;
	client.onMessageArrived = onMessageArrived;
	client.connect({onSuccess:onConnect});
	function onConnect() {
		client.subscribe("/foo");
	}
	function onConnectionLost(responseObject) {
		console.log("onConnectionLost:"+responseObject.errorMessage);
	}
	function onMessageArrived(message) {
		console.log("onMessageArrived:"+message.payloadString);
	}

```

**Comment by post2web** [comment]
I just connected to the websockets socket of the mosquitto server and everything works file.
Please close this issue.

**Comment by rafaelhss** [comment]
what was the solution ? I have the same issue.

**Comment by jpwsutton** [comment]
@rafaelhss  Does your Mosquitto server have websockets enabled?

**Comment by rafaelhss** [comment]
I am running mosquitto from this image: https://hub.docker.com/r/toke/mosquitto/

After reading your reply I put a mosquitto.conf file in /srv/mqtt/config folder and run this: 
docker run -ti -p 1883:1883 -p 9001:9001 -v /srv/mqtt/config:/mqtt/config:ro -v /srv/mqtt/log:/mqtt/log -v /srv/mqtt/data/:/mqtt/data/ --name mqtt toke/mosquitto

My mosquitto.conf file content is:
listener 1883
listener 1884
protocol websockets

I am trying to use this script: http://jsfiddle.net/rafaelhss/r9sdd1z2/

And, now, the server says: "1489655235: Opening websockets listen socket on port 1884."

But when I try to connect, nothing happens in the server and the browser console logs: WebSocket connection to 'ws://localhost:1884/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED.

So, I think you helped me and the issue has changed. Thank you.
