### ISSUE TITLE
Got "SecurityError: The operation is insecure.", when using locally with Firefox

### ISSUE THREAD

**Issue by bitfreak25** [eclipse/paho.mqtt.javascript#80]
I tried to use the library with Firefox 45.3.0 ESR. When I access the HTML like "localhost:/// [...]" it already works, but with "file:/// [...]" I get the above error in the console (pressing F12) and the library doesn't work.

As I delete the related code-snippets, it works, but I don't know if I breaks something. The related code-snippets are:

`if (!("localStorage" in global && global["localStorage"] !== null)) {
	throw new Error(format(ERROR.UNSUPPORTED, ["localStorage"]));
}`

and

`for (var key in localStorage)
	if (   key.indexOf("Sent:"+this._localKey) == 0
		|| key.indexOf("Received:"+this._localKey) == 0)
	this.restore(key);`

in line 750 and 795 (release 1.0.2).

With Chromium it works without this workaround, so the problem seems related to Firefox. Especially it seems related to the localStorage.

**Comment by jpwsutton** [comment]
@bitfreak25 I've tried re-creating this in my own copy of firefox 45.3.0 and found that it worked fine with no errors shown. Were you testing using the included utility that's in this repository?

<img width="1429" alt="screen shot 2016-09-02 at 11 08 03" src="https://cloud.githubusercontent.com/assets/1068763/18200662/cfd69694-70fd-11e6-9645-5c31e78e6409.png">

It could be related to other parts of the html page that you are running: http://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate

**Comment by bitfreak25** [comment]
Hi jpwsutton,

thanks for your effort, but I may already get the problem. When I activate my cookies (I've disabled it by default), it works. I also get the same error with Chromium, when deactivate my cookies there, with a more detailed error:

> Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Is it already necessary to work with the localStorage, as it breaks some clients with no activated cookies? At least, it should maybe documented somewhere.

**Comment by jpwsutton** [comment]
I believe that most browsers treat localstorage and cookies in similar ways:

> Treating persistent storage as cookies
If users attempt to protect their privacy by clearing cookies without also clearing data stored in the local storage area, sites can defeat those attempts by using the two features as redundant backup for each other. User agents should present the interfaces for clearing these in a way that helps users to understand this possibility and enables them to delete data in all persistent storage features simultaneously. [COOKIES]
https://html.spec.whatwg.org/multipage/webstorage.html

Localstorage is required to allow true QoS1 and QoS2 to work by acting as the persistence layer incase the client side application crashes.

Adding some documentation about how disabling localstorage or cookies breaks this is a good idea though. I'll add it to the Readme or Wiki.

**Comment by jpwsutton** [comment]
Wiki page added here: https://github.com/eclipse/paho.mqtt.javascript/wiki/LocalStorage-Restrictions
