### ISSUE TITLE
TLS javascript paho client is available

### ISSUE THREAD

**Issue by Hephze** [eclipse/paho.mqtt.javascript#88]
Any TLS javascript paho client is available ?

**Comment by jpwsutton** [comment]
Hi, Yes the Paho Javascript client supports Secure Websockets (wss) using TLS.
You can try it out here: http://www.eclipse.org/paho/clients/js/utility/
Change the Host and port to those of your Broker with WSS support and tick the SSL box (We need to change that to say TLS).

**Comment by Hephze** [comment]
Actually i need a tls javascript paho client for connecting to mosquitto server without websocket

**Comment by Hephze** [comment]
https://eclipse.org/paho/clients/golang/ the link says that we can connect our client to broker using tls. Where is the javascript library for this.

**Comment by jpwsutton** [comment]
Do you mean TLS over TCP? If that's the case then the Paho Javascript client will not be able to do that as it is Websocket only. However MQTT.js is capable of making TCP TLS connections to MQTT Brokers: https://www.npmjs.com/package/mqtt

**Comment by Hephze** [comment]
Thanks for the quick response. Let me clarify my question. Is there any javascript client available for connecting to brokers via tls.

**Comment by jpwsutton** [comment]
Both the Paho Javascript client and the MQTT.js client can connect using TLS. 

However the Paho Client can only use WebSockets and only works in Web Browsers, whereas MQTT.js Can do both Websockets and pure TCP and works on Node.js

**Comment by Hephze** [comment]
Thanks. Is there any JavaScript client library for connecting mobile applications to brokers using tls?

**Comment by jpwsutton** [comment]
Is your mobile application running in a web browser? And does your broker support WebSockets or Just TCP?

**Comment by Hephze** [comment]
our mobile application is a cross platform application (cordova) and our broker supports tls and tcp. so we need a javascript client for connecting to such a broker.

**Comment by jpwsutton** [comment]
Both Paho and MQTT.js will work in cordova, however if your broker only supports TCP then you will only be able to use MQTT.js

**Comment by duythang** [comment]
@jpwsutton. Hello, i am confusing that why Paho does not use key when it applies  TLS. In addtion, you said that Paho support TLS. However, i saw that in "http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html" with "connect" method, there is only "useSSL" option without TLS. So, does Paho exactly support TLS ?. Thank you

**Comment by miketran78727** [comment]
@duythang From the application point of view, you will only need to set useSSL to true.  The Paho JavaScript client will establish a secure websocket connection (i.e. wss://) .  As for version of TLS (or SSL), it is dependent on the security setting of the browser that your application is running in.  For example, if the browser security setting is TLS 1.2, then TLS 1.2 will be used.

**Comment by P47K0** [comment]
Is it possible to use client authentication with a certificate instead of username/password with the Paho javascript client? If so, how?

**Comment by 0xc0d3r** [comment]
@P47K0 Did you figure it out how to do with certificates?

@jpwsutton Is it possible to use client authentication with a certificates with the Paho javascript client? If so, how?

**Comment by P47K0** [comment]
No, I don't think it is possible currently.

**Comment by 0xc0d3r** [comment]
Thanks for the reply @P47K0 

I am proceeding with [aws-iot-device-sdk-js](https://github.com/aws/aws-iot-device-sdk-js) using Cognito.

**Comment by ahmadalibaloch** [comment]
https://github.com/mqttjs

**Comment by bharanidharan81** [comment]
From the application point of view, you will only need to set useSSL to true. The Paho JavaScript client will establish a secure websocket connection (i.e. wss://) . For two authentication, client requires a certificate to establish the connection.  Is it possible to use client authentication with a certificate instead of username/password with the Paho javascript client? If so, how?

**Comment by bharanidharan81** [comment]
In two-way authentication, the client requires certificate to establish the connection.  Is it possible to use client authentication with a certificate instead of username/password with the Paho javascript client? If so, how? please share the tutorials and documentation to proceed.

**Comment by jigneshk5** [comment]
This might help: https://github.com/eclipse/paho.mqtt.javascript/issues/187#issuecomment-594450347
