### ISSUE TITLE
Cannot keep client listening continually. 

### ISSUE THREAD

**Issue by NancyZY** [eclipse/paho.mqtt.javascript#89]
Hi,I have read this website [(https://eclipse.org/paho/clients/js/)], I am using mqttws31.min.js and have an issue that I cannot solved it . When subscribed to a client using the code below I receive one message back and then it will not receive any further messages, I have Googled all day but cannot find the documentation anywhere, please could you point me in the right direction? 
`<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js" type="text/javascript"></script>
  <script type="text/javascript">    
    var wsbroker = "test.mosquitto.org";  //mqtt websocket enabled broker
    var wsport = 8080 // port for above
    var client = new Paho.MQTT.Client(wsbroker, wsport,
        "clientId-pMOtohS8Xj");
    client.onConnectionLost = function (responseObject) {
      console.log("connection lost: " + responseObject.errorMessage);
    };
    client.onMessageArrived = function (message) {
      console.log(message.destinationName, ' -- ', message.payloadString);
    };
    var options = {
      timeout: 3,
      onSuccess: function () {
        console.log("mqtt connected");        
        client.subscribe('/World', {qos: 1});              
      },
      onFailure: function (message) {
        console.log("Connection failed: " + message.toString(),message.errorMessage);
      }
    };
  function init() {
      client.connect(options);
  }
    </script>
  </head>
  <body onload="init();">
  </body>
</html>
`
and I saw information from chrome console for processing : when I published the message at websocket client at first time, the console  can show correctly, when I published second, then the console show "**connection lost: AMQJS0008I Socket closed.**", but the websocket-client hints publish successfully.

**Comment by jpwsutton** [comment]
Hi, I've just tried your code and it seems to work fine. I used the iot.eclipse.org:80 broker and gave it a new client ID and was able to receive many messages that I published to that topic. Are you using a unique Client ID for both your Publishing app and this subscribing app?

**Comment by NancyZY** [comment]
Thx for your reply so soon, I used test.mosquitto.org as broker and gave html page a unique clientID, I published message by  websocket-client , then check if chrome console is right.Am I right process?

PS: I have ever tried use the Baidu Cloud IoL as broker, but connection failed in chrome console.(client was well done) So I gave it up.

**Comment by NancyZY** [comment]
hi, jpwsutton. I already solved my issues, because the clientId for websocket-client and html page should be different, but I am not did this way. It's my fault.You can close the issues.

**Comment by NancyZY** [comment]
How to deal with the reconnection,? I try to in **onConnectionLost** method call the connection method, Is it right action?  and client id will be same as before? I wrote the below code as client id:
```js
var client = new Paho.MQTT.Client(wsbroker, wsport, "web_" + parseInt(Math.random() * 100, 10));
```

**Comment by jpwsutton** [comment]
Assuming that your code is the only code using that client ID, then you can re-use the client ID (And probably should).

If you change your client ID every time you connect, you won't receive any undelivered QoS 1 and 2 messages, you will also loose any subscriptions and will have to resubscribe.
