### ISSUE TITLE
Get current client status

### ISSUE THREAD

**Issue by Alphatiger** [eclipse/paho.mqtt.javascript#90]
Hi can we get the current client status

The idea is before sending a message check the client connection status if disconnected then reconnect and then send message

**Comment by kenvernaillenvub** [comment]
Paho.MQTT.Client#send
@throws {InvalidState} if the client is not connected.

-> line 915
```
if (!this.connected)
	throw new Error(format(ERROR.INVALID_STATE, ["not connected"]));
```

Normally you should be able to catch this Error. (Didn't try it yet)

**Comment by michaeljota** [comment]
try-catch code in JS is irregularly expensive. There is no exposition of the status connection? Is better to check, like the code does, if the client is connected, that wrap the code in a try-catch block.
