### ISSUE TITLE
API Documentation for subscribe

### ISSUE THREAD

**Issue by gfinocchiaro** [eclipse/paho.mqtt.javascript#92]
Hi,

looking at the API documentation for the [subscribe method](http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html#subscribe), it is reported that the
_subscribeOptions.onFailure_ callback accepts a response object containing two fields (errorCode and erroreMessage). But it seems that in the implementation only the errorCode is actually used, as you can see from the code excerpt below (rows 871-873):

`
if (subscribeOptions.onFailure) {
			wireMessage.onFailure = function(errorCode) {subscribeOptions.onFailure({invocationContext:subscribeOptions.invocationContext,errorCode:errorCode});};
`

**Comment by jpwsutton** [comment]
From what I can see in the API Docs, onFailure does not mention an error Message:

> {function} subscribeOptions.onFailure
> -called when the subscribe request has failed or timed out. A single response object parameter is passed to the onFailure callback containing the following fields:
> 1. invocationContext - if set in the subscribeOptions.
> 2. errorCode - a number indicating the nature of the error.


Are you thinking of unSubscribeOptions.onFailure? Which does contain an error message?

http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html#unsubscribe

https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/mqttws31.js#L901

**Comment by gfinocchiaro** [comment]
I was wrong about the published API Docs, instead the error is in the API Docs embedded in the source code:

[https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/mqttws31.js#L1826](https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/mqttws31.js#L1826)

**Comment by gfinocchiaro** [comment]
Any news on this?

**Comment by jpwsutton** [comment]
I've added this to the 1.3.0 milestone, Hopefully we should be able to add the error message in, otherwise I'll remove the incorrect documentation.

**Comment by jpwsutton** [comment]
I've added the Error message in now. The fix is available in the develop branch.
