### ISSUE TITLE
Failed to connect: AMQJS0007E Socket error:undefined

### ISSUE THREAD

**Issue by GitHubDelphi** [eclipse/paho.mqtt.javascript#98]
Today I downloaded the the latest Paho clients js utility.
While connecting the client it gives me error: Failed to connect: AMQJS0007E Socket error:undefined

I have used the identical parameters as with the *hosted* Javascript client utility here: https://www.eclipse.org/paho/clients/js/utility/

The *hosted* Javascript client utility works fine.

This seems to be a pretty basic thing.  I would appreciate some help on how to resolve this issue.

Thank you.

**Comment by jpwsutton** [comment]
Couple of questions:

1. Are you trying to connect to iot.eclipse.org? If so, you need to use TLS and target port 443.
2. Which branch did you download from? Master, or Develop?
3. Could you check the Console log to see if any other errors are shown?

**Comment by GitHubDelphi** [comment]
Resolved.  I appreciate your ultra fast response!

1. Yes
2. Master
3. No other errors.

**Comment by jpwsutton** [comment]
Glad I could help!
